fix: install prerequisites for windows

diff --git a/.github/workflows/github_release.yml b/.github/workflows/github_release.yml
--- a/.github/workflows/github_release.yml
+++ b/.github/workflows/github_release.yml
@@ -165,9 +165,9 @@ jobs:
             echo "PROTOC=$(command -v protoc)" >> $GITHUB_ENV
             ;;
           windows-*)
-            powershell -NoProfile -NonInteractive -Command "choco install protoc -y --no-progress"
-            powershell -NoProfile -NonInteractive -Command "if (-not (Get-Command protoc -ErrorAction SilentlyContinue)) { Write-Error 'protoc not installed properly on Windows, exiting with error...'; exit 1 }"
-            powershell -NoProfile -NonInteractive -Command "Add-Content -Path $env:GITHUB_ENV -Value ('PROTOC=' + (Get-Command protoc -ErrorAction Stop).Source)"
+            powershell -NoProfile -NonInteractive -Command 'choco install protoc -y --no-progress'
+            powershell -NoProfile -NonInteractive -Command 'if (-not (Get-Command protoc -ErrorAction SilentlyContinue)) { Write-Error "protoc not installed properly on Windows, exiting with error..."; exit 1 }'
+            powershell -NoProfile -NonInteractive -Command 'Add-Content -Path $Env:GITHUB_ENV -Value ("PROTOC=" + (Get-Command protoc -ErrorAction Stop).Source)'
             ;;
         esac
         echo "protoc has been installed successfully"
